### ISSUE TITLE
Test erroné

### ISSUE THREAD

**Issue by Akulen** [Kegnarok/Maison-close#1]
Le test typing/bad/florentin-types-mut-rec.adb est listé comme devant planter lors du typage alors qu'il s'agit d'un code tout à fait valide.

**Comment by FlorentinGuth** [comment]
Ben en mini-Ada on ne peut pas faire un access d'un record, mais c'est vrai qu'en Ada il est valide, je vais le jarter il ne sert à rien

**Comment by Akulen** [comment]
(Euh `access` en mini-ada sert que pour faire un `access record`)

**Comment by FlorentinGuth** [comment]
oui c'est ce que je voulais dire
