### ISSUE TITLE
Vars In Out

### ISSUE THREAD

**Issue by MartinusR** [Kegnarok/Maison-close#2]
Est-ce que quelqu'un aurait un exemple dans lequel il serait pertinent de refuser de passer une même variable In out en argument à une fonction ?
(Comme gnat le refuse gentiment dans le test d'alexis)

**Comment by FlorentinGuth** [comment]
C'est vrai que c'est bizarre de vouloir faire ça, si par exemple tu as une fonction qui ajoute un au premier arg et multiplie le deuxième par 2 tu as pas trop envie que le mec passe deux fois le même, parce que l'ordre n'est pas défini

**Comment by MartinusR** [comment]
Ben y a quand même un ordre non ?

**Comment by FlorentinGuth** [comment]
oui mais c'est pas défini de l'extérieur

**Comment by MartinusR** [comment]
Sauf que c'est le programmeur qui l'écrit quand même, donc il sait ce qu'il met dans sa fonction

**Comment by FlorentinGuth** [comment]
ça pourrait être une fonction de bibliothèque

**Comment by MartinusR** [comment]
Je demande à voir !
Enfin bref tout ça pour dire que c'est impossible de le détecter proprement donc que le test devrait pas etre la et m'empecher de faire plein de 100%
