### ISSUE TITLE
Nouveaux tests leftVal

### ISSUE THREAD

**Issue by Lucas-84** [Kegnarok/Maison-close#3]
Les nouveaux fichiers `typing/bad/lionel_leftValFun.adb` et `typing/bad/lionel_leftValAcc.adb` me paraissent suspects : je pense qu'il manque un point virgule au premier, et pour le deuxième, la ligne 13 devrait plutôt être une erreur de syntaxe en Mini-Ada, parce que dans la grammaire, `<accès>` ne se réduit qu'à `<ident>` ou `<expr>.<ident>`, mais pas à `<expr>`.
[D'ailleurs c'est un peu bizarre, dans la plupart des langages le truc à gauche d'une affectation ça doit être une expression qui est en plus une  lvalue, mais visiblement il était pas trop prévu de parler initialement de "valeur gauche" dans le sujet.]

En tout cas, c'est ce que me répond mon compilo, et ça m'arrangerait que les vôtres soient d'accord avec ça. :p

**Comment by dwarfmaster** [comment]
Je plussoie. Pour `leftValAcc`, on pourrait éventuellement le déplacer dans `opt/typing/bad` au lieu de le mettre dans `syntax/bad`.

**Comment by Liozou** [comment]
C'est déplacé dans `syntax/bad` pour respecter strictement l'énoncé. Ce qui est dans `opt/`, ce sont surtout des vérifications supplémentaires, pour se rapprocher du comportement de gnat je crois...
