### ISSUE TITLE
Test faux? 

### ISSUE THREAD

**Issue by TheLortex** [Kegnarok/Maison-close#4]
Le test /syntax/good/testfile-lexical-2.adb plante avec gnat et c'est normal parce que l'entier 2147483648 n'est pas représentable en entier signé 32 bits.

**Comment by TWal** [comment]
Selon la spec du prof ça doit être accepté : "Les constantes entières doivent être comprises entre 0 et 2^31, inclus."
(d'ailleurs c'est un test du prof donc ça peut être pas mal de l'accepter :-P)
Je pense que c'est pour éviter qu'on doive prendre en compte le - pour accepter -2147483648 qui lui est représentable en signé sur 32 bits
