### ISSUE TITLE
OutParams

### ISSUE THREAD

**Issue by Akulen** [Kegnarok/Maison-close#6]
Je ne suis pas d'accord que `typing/bad/mathieu-outparams.adb` devrait echouer. Si la meme variable est donnee deux fois en in out, alors les deux parametres pointent vers la meme variable et donc la modifient tous les deux.

**Comment by Ekdohibs** [comment]
C'est encore une différence entre MiniAda et Ada. Pour moi, un grand nombre de ces tests devraient être dans `opt/`.

**Comment by athibaul** [comment]
En fait ce test existe déjà, c'est `opt/typing/bad/alexis-inout-1.adb`, qui a effectivement été mis dans `opt/`.

**Comment by pnmadelaine** [comment]
j'ai supprimé le fichier en question, puisque de toute manière il faisait doublon
